import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]
live_config_reload = true

[window]
decorations = "None"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[window.padding]
x = 2
y = 2
