#!/usr/bin/env zsh

addToPath() {
  if [[ "$PATH" != *"$1"* ]]; then
      export PATH=$PATH:$1
  fi
}

addToPathFront() {
  if [[ "$PATH" != *"$1"* ]]; then
      export PATH=$1:$PATH
  fi
}

function showPath() {
  echo $PATH | tr ':' '\n'
}

tmux-which-key() {
  tmux show-wk-menu-root ;
}
